all: #explicitly specify 'all' which includes every host defined in this inventory file (implicitly if not sepcified always present)
  hosts: #ungrouped hosts which are not part of any other groups
    localhost:
  vars: #inventory vars
    ansible_user: saltanov
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh #to skip ssh connection entirely just specify 'local'
    ansible_port: 2223
    ansible_host: 127.0.0.1
    #ansible_ssh_private_key_file: local ssh config file is used to define key
  children: #use as we want to create a parent group that could encompasses multiple child groups
    production: 
      children:
        vagrant_vms:
          hosts:
            server1: #alias instead of ip/dns name
              ansible_user: vagrant #inventory host vars
            server2:
              ansible_user: root
          vars: #inventory group vars
            ansible_python_interpreter: /usr/bin/python3
            ansible_connection: ssh
            ansible_port: 22
            ansible_host: 192.168.56.4
      vars: #inventory group parent vars
        ansible_ssh_private_key_file: /home/saltanov/.ssh/ansible_key
          